behaviors:
  Player1Agent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 20480
      learning_rate: 3.0e-3
      beta: 5.0e-4
      epsilon: 0.25
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 32
      num_layers: 2
      memory: 
        memory_size: 128
        sequence_length: 128
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 10000000
    time_horizon: 256
    summary_freq: 5000
    checkpoint_interval: 100000
    threaded: true


