behaviors:
  Player1Agent:
    trainer_type: ppo
    hyperparameters:
      batch_size: 512
      buffer_size: 8192
      learning_rate: 7.0e-4
      beta: 5.0e-3
      epsilon: 0.15
      lambd: 0.95
      num_epoch: 7
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 10000000
    time_horizon: 2048
    summary_freq: 5000
    checkpoint_interval: 50000
    threaded: true


